### ISSUE TITLE
Crash seen while trying to create a routed network in vcd

### ISSUE THREAD

**Issue by rathinikunj** [vmware/go-vcloud-director#302]
I was trying to create routed networks in vcd using below code and see a panic.
The same code had worked earlier but i see this crash consistently now.

I have tried with vcd provider version 2.7.0 and 2.8.0 and terraform version **Terraform v0.12.23**

This code change is done almost at the same location where the panic points to:

https://github.com/vmware/go-vcloud-director/commit/bcfd6a2ef334826f9b95aa91b16fcf93cc1f22aa#diff-4b1ced23b0536f2f76a2bd8866f8deaf

**Code**
```
locals {
  org = "asd"
  vdc = "asd-2"
  edge_gateway = "edge1"
  number_of_networks_small = 2
  network_name_prefix_small = "vdc2-net"
  subnet_prefix_small = "192.169."
  dns1 = "10.79.204.2"
}

resource "vcd_network_routed" "net" {
  org  = local.org
  vdc  = local.vdc
  count = local.number_of_networks_small
  #description = "Routed Network"
  name = "${local.network_name_prefix_small}${count.index + 1}"
  edge_gateway = local.edge_gateway
  gateway = "${local.subnet_prefix_small}${count.index + 1}.254"
  shared = "true"
  interface_type = "distributed"
  dns1 = local.dns1
  dhcp_pool {
    start_address = "${local.subnet_prefix_small}${count.index + 1}.51"
    end_address = "${local.subnet_prefix_small}${count.index + 1}.253"
  }
  static_ip_pool {
    start_address = "${local.subnet_prefix_small}${count.index + 1}.1"
    end_address = "${local.subnet_prefix_small}${count.index + 1}.50"
  }
}
```
**Panic dump**

> 2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: panic: runtime error: invalid memory address or nil pointer dereference
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xda5989]
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4:
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: goroutine 32 [running]:
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: github.com/vmware/go-vcloud-director/v2/govcd.(*EdgeGateway).AddDhcpPool(0xc0001f60d0, 0xc00016c400, 0xc0001f66a0, 0x1, 0x1, 0x1, 0x0, 0x0, 0xc000293750)
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/vmware/go-vcloud-director/v2/govcd/     edgegateway.go:70 +0x1b9
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: github.com/terraform-providers/terraform-provider-vcd/v2/vcd.resourceVcdNetworkRoutedCreate(0xc0002cf110, 0x1140e60, 0xc00051a410, 0x0, 0x0)
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vcd/resource_vcd_network_routed.go:283 +0xd34
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0004a2800, 0xc00025aaf0, 0xc000423ee0, 0x1140e60, 0xc00051a410, 0xc000636901,      0xc000079748, 0xfe6680)
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/  schema/resource.go:305 +0x3b4
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000544300, 0xc000293a68, 0xc00025aaf0, 0xc000423ee0, 0xc000509828, 0xc0000ccf30,   0xfe8360)
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/  schema/provider.go:294 +0x18f
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e048, 0x141ab20, 0xc00025ced0, 0xc000271080, 0xc00000e048, 0xc00025ced0, 0xc0005b9bd0)
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x884
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1112880, 0xc00000e048, 0x141ab20, 0xc00025ced0,            0xc000271020, 0x0, 0x141ab20, 0xc00025ced0, 0xc000428000, 0x381)
2020-04-28T09:36:10.231Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3189 +0x23e
2020-04-28T09:36:10.232Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000f0160, 0x14286e0, 0xc000595200, 0xc00016cf00, 0xc000158780, 0x1c91200, 0x0, 0x0, 0x0)
2020-04-28T09:36:10.232Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vendor/google.golang.org/grpc/server.go:995 +0x466
2020-04-28T09:36:10.232Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc0000f0160, 0x14286e0, 0xc000595200, 0xc00016cf00, 0x0)
2020-04-28T09:36:10.232Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vendor/google.golang.org/grpc/server.go:1275 +0xda6
2020-04-28T09:36:10.232Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000be3b0, 0xc0000f0160, 0x14286e0, 0xc000595200, 0xc00016cf00)
2020-04-28T09:36:10.232Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vendor/google.golang.org/grpc/server.go:710 +0x9f
2020-04-28T09:36:10.232Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-04-28T09:36:10.232Z [DEBUG] plugin.terraform-provider-vcd_v2.7.0_x4:   /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vcd/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020-04-28T09:36:10.235Z [DEBUG] plugin: plugin process exited: path=/home/aviuser/avi-openshift/avi-dev/test/scripts/jd-scripts/misc/terraform/create_vcd_networks/.terraform/plugins/linux_amd64/terraform-provider-vcd_v2.7.0_x4       pid=2049 error="exit status 2"

**Comment by Didainius** [comment]
Hello @rathinikunj ,
Thanks for this issue. It should actually go to terraform-provider-vcd, but nonetheless the issue is interesting. 
Which version of vCD are you using?

**Comment by rathinikunj** [comment]
Hi @Didainius 

I have filed another one there, wanted to close this one. 
I am seeing this issue with both 2.7.0 and 2.8.0 versions.

The issue in terraform-provider-vcd - https://github.com/terraform-providers/terraform-provider-vcd/issues/500
